/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//Variables globales
uint8_t variable1 = 0;
uint8_t variable2 = 255;
uint8_t variable3 = 10;
uint16_t result = 0;


int main(void)
{
	/*
	//Definimos mi variable 0.1
	uint8_t mi_variable = 42;

    //0.2

    uint8_t dec = 65;
    uint8_t hex = 0x41;
    uint8_t bin = 0b01000001;
    //son iguales

	//0.3

    uint8_t  a = 255;
    uint16_t b = 255;
    uint32_t c = 255;
    uint8_t  d = 256; //Se sale de la arquitectura por eso marca cero

    uint8_t  e = 257; //Al igual que el caso anterior se desborda y vuelve a empezar

	//0.4

	uint8_t a = 200;
    int8_t  b = 200;
    int8_t  c = -1;

	//0.5

	int8_t  x = 127;
	x = x + 1;

	uint8_t y = 255;
	y = y + 1;
	/* Tanto 'x' como 'y' presentan un overflow, es decir, llegan a su valor maximo se desbordan y
	 vuelven a empezar en el valor minimo, -128 para 'x' por ser variable de 8 bit con signo
	 y 0 para 'y' por ser variable de 8 bit sin signo */
/*
	//0.6
	 *
	uint8_t result;
	result = 0x0F + 0x01;
	result = 0xFF + 0x01;
	result = 0xA0 + 0x5F;
	result = 0xA0 + 0x60;

	//0.7
	uint8_t x = 0;
	x = 0x01;

	x = 0x02;

	x = 0x04;

	x = 0x08;

	x = 0x10;

	x = 0x20;

	x = 0x40;

	x = 0x80;


	uint8_t a = 5;
	uint8_t b = 0;
	uint8_t c = 255;

	uint8_t r1 = !a;
	uint8_t r2 = !b;
	uint8_t r3 = !c;
	uint8_t r4 = ~c;

	uint8_t r5 = ~a; //11111010
	*/

/*

	//Semana1

	//1.1
	uint8_t a          = 17;
	uint8_t b          = 5;
	uint8_t div_result = a / b;
	uint8_t mod_result = a % b;
	uint8_t mul_result = a * b;

	//1.2
	uint8_t x   = 200;
	uint8_t y   = 100;
	uint8_t sum = x + y;

	//1.3

	uint8_t val = 3;

	uint8_t left1  = val << 1;
	uint8_t left2  = val << 2;
	uint8_t left3  = val << 3;
	uint8_t right1 = val >> 1;
	*/

	//1.4 bloque if, if-else
	if (variable2 + variable3 != 0){
		result = variable2 + variable3;

	}
	if (variable1 == 0){
			result = 0;

	}
	if (variable3 >= variable1){
		result = variable2 + variable3;

	}
	if (variable2 + variable3 == 0){
			result = variable2 + variable3;

		}else{
		result = 0;
		}
		if (variable1 != 0){
				result = 0;

		}else {
		result = variable2 + variable3;
		}
		if (variable3 <= variable1){
			result = variable2 + variable3;

		}else {
			result = 0;
		}
    /* Loop forever */
	while (1)
	{
// Quitamos el for
	}
	return 0;
}
